<?php
declare(strict_types=1);

/**
 * Catálogo de ropa corporativa: 11 líneas de producto con 70 prendas en total.
 *
 * NOTA SOBRE LAS IMÁGENES: todas las fotos de producto se sirven desde
 * tworldstore.cl, un dominio externo del proveedor. No tenemos los archivos en
 * local, por lo que se mantienen esas URL, pero conviene autoalojarlas en
 * /assets/img/catalogo/ (en WebP y con varios tamaños) para no depender de un
 * tercero: hoy el rendimiento, la caché y la disponibilidad del catálogo
 * quedan fuera de nuestro control, y cualquier cambio en ese sitio rompe las
 * 70 imágenes. Mientras eso ocurra, cada .prod-img lleva
 * data-ocultar-si-falla para degradar sin romper la maquetación.
 *
 * Estructura de cada línea:
 *   tab         → etiqueta corta para la barra de navegación de líneas
 *   badge       → distintivo que se muestra sobre el título
 *   titulo      → título de la línea; 'destacado' es la parte resaltada en <em>
 *   descripcion → texto introductorio de la línea
 *   productos   → lista de prendas: sku, nombre, alt, imagen, especificacion,
 *                 colores (hex => nombre legible) y texto del botón (cta)
 */
function catalogo_lineas(): array {
    return [

        'classic'     => [
            'tab'         => 'Classic',
            'badge'       => 'Classic Line',
            'titulo'      => 'Clásica y',
            'destacado'   => 'versátil',
            'descripcion' => 'Camisas Oxford, Trevira y micropolar para el día a día corporativo. Disponibles en hombre y mujer, manga larga y corta.',
            'productos'   => [
                [
                    'sku'            => '06012',
                    'nombre'         => 'Camisa Oxford Classic M/L Hombre',
                    'alt'            => 'Camisa Oxford Classic',
                    'imagen'         => 'https://tworldstore.cl/554-large_default/camisa-oxford-classic-ml-hombre-55-alg-45-poly.jpg',
                    'especificacion' => '55% Poliéster / 45% Algodón · Manga Larga',
                    'colores'        => ['#fff' => 'Blanco', '#a8c5da' => 'Celeste Claro', '#9e9e9e' => 'Gris'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '06052',
                    'nombre'         => 'Blusa Oxford Classic M/L Mujer',
                    'alt'            => 'Blusa Oxford Classic Mujer',
                    'imagen'         => 'https://tworldstore.cl/563-large_default/blusa-oxford-classic-ml-mujer.jpg',
                    'especificacion' => 'Manga Larga · Corte femenino',
                    'colores'        => ['#fff' => 'Blanco', '#a8c5da' => 'Celeste Claro'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '06271',
                    'nombre'         => 'Camisa Oxford Light M/L Hombre',
                    'alt'            => 'Camisa Oxford Light',
                    'imagen'         => 'https://tworldstore.cl/4691-large_default/camisa-oxford-light-ml-hombre.jpg',
                    'especificacion' => 'Tela liviana · Manga Larga · Varios colores',
                    'colores'        => ['#fff' => 'Blanco', '#a8c5da' => 'Celeste Claro', '#5b8db8' => 'Celeste Oscuro'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '06281',
                    'nombre'         => 'Blusa Oxford Light M/L Mujer',
                    'alt'            => 'Blusa Oxford Light',
                    'imagen'         => 'https://tworldstore.cl/618-large_default/blusa-oxford-light-ml.jpg',
                    'especificacion' => 'Tela liviana · Corte femenino · Manga Larga',
                    'colores'        => ['#fff' => 'Blanco', '#a8c5da' => 'Celeste Claro', '#5b8db8' => 'Celeste Oscuro'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '06291',
                    'nombre'         => 'Camisa Trevira Light M/L Hombre',
                    'alt'            => 'Camisa Trevira Light',
                    'imagen'         => 'https://tworldstore.cl/1438-large_default/camisa-trevira-light-ml-hombre.jpg',
                    'especificacion' => '55% Poliéster / 45% Algodón · Manga Larga',
                    'colores'        => ['#fff' => 'Blanco', '#a8c5da' => 'Celeste Claro', '#5b8db8' => 'Celeste Oscuro'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '03079',
                    'nombre'         => 'Micropolar Tela Plana Hombre M/L',
                    'alt'            => 'Micropolar Tela Plana',
                    'imagen'         => 'https://tworldstore.cl/3684-large_default/micropolar-tela-plana-hombre-ml.jpg',
                    'especificacion' => '100% Poliéster · Tela plana · Manga Larga',
                    'colores'        => ['#555' => 'Gris Oscuro', '#1a1a1a' => 'Negro', '#1a4f8b' => 'Azul Royal', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '03089',
                    'nombre'         => 'Micropolar Tela Plana Mujer M/L',
                    'alt'            => 'Micropolar Tela Plana Mujer',
                    'imagen'         => 'https://tworldstore.cl/5920-large_default/micropolar-tela-plana-mujer-ml.jpg',
                    'especificacion' => '100% Poliéster · Tela plana · Corte femenino',
                    'colores'        => ['#555' => 'Gris Oscuro', '#1a1a1a' => 'Negro', '#1a4f8b' => 'Azul Royal', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '06241',
                    'nombre'         => 'Camisa Oxford Classic M/C Hombre',
                    'alt'            => 'Camisa Oxford Classic M/C',
                    'imagen'         => 'https://tworldstore.cl/5887-large_default/camisa-oxford-classic-mc-hombre.jpg',
                    'especificacion' => 'Oxford · Manga Corta · Varios colores',
                    'colores'        => ['#fff' => 'Blanco', '#a8c5da' => 'Celeste Claro'],
                    'cta'            => 'Cotizar con bordado',
                ],
            ],
        ],

        'poleras'     => [
            'tab'         => 'Poleras',
            'badge'       => 'Poleras',
            'titulo'      => 'Poleras',
            'destacado'   => 'cuello redondo',
            'descripcion' => 'Poleras básicas y técnicas de cuello redondo para hombre y mujer. Algodón, Dryfresh y Work Dry. Manga larga y manga corta. Ideales para estampado.',
            'productos'   => [
                [
                    'sku'            => '01014',
                    'nombre'         => 'Polera M/C Hombre 100% Algodón',
                    'alt'            => 'Polera M/C Hombre 100% Algodón',
                    'imagen'         => 'https://tworldstore.cl/4306-large_default/polera-mc-hombre-100-alg.jpg',
                    'especificacion' => '100% Algodón · Cuello redondo · Manga Corta',
                    'colores'        => ['#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#9e9e9e' => 'Gris', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con estampado',
                ],
                [
                    'sku'            => '01105',
                    'nombre'         => 'Polera M/C Mujer 95% Alg 5% Spandex',
                    'alt'            => 'Polera M/C Mujer',
                    'imagen'         => 'https://tworldstore.cl/4485-large_default/polera-mc-mujer-95-alg-5-spx.jpg',
                    'especificacion' => '95% Algodón / 5% Spandex · Cuello redondo · Manga Corta',
                    'colores'        => ['#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#9e9e9e' => 'Gris'],
                    'cta'            => 'Cotizar con estampado',
                ],
                [
                    'sku'            => '01201',
                    'nombre'         => 'Polera Essential Soft Hombre M/L',
                    'alt'            => 'Polera Essential Soft M/L',
                    'imagen'         => 'https://tworldstore.cl/1363-large_default/polera-essential-soft-hombre-ml.jpg',
                    'especificacion' => 'Suave al tacto · Cuello redondo · Manga Larga',
                    'colores'        => ['#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#9e9e9e' => 'Gris', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con estampado',
                ],
                [
                    'sku'            => '01181',
                    'nombre'         => 'Polera Essential Soft Hombre M/C',
                    'alt'            => 'Polera Essential Soft M/C',
                    'imagen'         => 'https://tworldstore.cl/1360-large_default/polera-essential-soft-hombre-mc.jpg',
                    'especificacion' => 'Suave al tacto · Cuello redondo · Manga Corta',
                    'colores'        => ['#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#9e9e9e' => 'Gris', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con estampado',
                ],
                [
                    'sku'            => '01176',
                    'nombre'         => 'Polera Dryfresh Smooth M/L Hombre',
                    'alt'            => 'Polera Dryfresh Smooth M/L',
                    'imagen'         => 'https://tworldstore.cl/4382-large_default/polera-dryfresh-smooth-ml-hombre-cert.jpg',
                    'especificacion' => 'Secado rápido · Cuello redondo · Manga Larga',
                    'colores'        => ['#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con estampado',
                ],
                [
                    'sku'            => '01156',
                    'nombre'         => 'Polera Dryfresh Smooth M/C Hombre',
                    'alt'            => 'Polera Dryfresh Smooth M/C',
                    'imagen'         => 'https://tworldstore.cl/4406-large_default/polera-dryfresh-smooth-mc-hombre.jpg',
                    'especificacion' => 'Secado rápido · Cuello redondo · Manga Corta',
                    'colores'        => ['#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con estampado',
                ],
                [
                    'sku'            => '01241',
                    'nombre'         => 'Polera Work Dry Hombre M/Larga',
                    'alt'            => 'Polera Work Dry M/L',
                    'imagen'         => 'https://tworldstore.cl/4430-large_default/polera-work-dry-hombre-mlarga.jpg',
                    'especificacion' => 'Work Dry · Cuello redondo · Manga Larga',
                    'colores'        => ['#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#9e9e9e' => 'Gris', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con estampado',
                ],
                [
                    'sku'            => '01221',
                    'nombre'         => 'Polera Work Dry Hombre M/Corta',
                    'alt'            => 'Polera Work Dry M/C',
                    'imagen'         => 'https://tworldstore.cl/2805-large_default/polera-work-dry-hombre-mcorta.jpg',
                    'especificacion' => 'Work Dry · Cuello redondo · Manga Corta',
                    'colores'        => ['#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#9e9e9e' => 'Gris', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con estampado',
                ],
            ],
        ],

        'polo'        => [
            'tab'         => 'Polo / Piqué',
            'badge'       => 'Polo / Piqué',
            'titulo'      => 'Polo piqué',
            'destacado'   => 'cuello con botones',
            'descripcion' => 'Poleras polo de cuello con botones en tela piqué 60% algodón 40% poliéster. Manga larga y manga corta para hombre y mujer. Ideales para bordado con tu marca.',
            'productos'   => [
                [
                    'sku'            => '02146',
                    'nombre'         => 'Polera Polo M/L Hombre Piqué',
                    'alt'            => 'Polera Polo M/L Hombre',
                    'imagen'         => 'https://tworldstore.cl/4522-large_default/polera-polo-ml-hombre-60-alg-40-poly.jpg',
                    'especificacion' => '60% Algodón / 40% Poliéster · Piqué 230 gr · Manga Larga',
                    'colores'        => ['#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#1e3a6e' => 'Azul', '#c0392b' => 'Rojo'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '02136',
                    'nombre'         => 'Polera Polo M/C Hombre Piqué',
                    'alt'            => 'Polera Polo M/C Hombre',
                    'imagen'         => 'https://tworldstore.cl/4554-large_default/polera-polo-mc-hombre-60-alg-40-poly.jpg',
                    'especificacion' => '60% Algodón / 40% Poliéster · Piqué · Manga Corta',
                    'colores'        => ['#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#1e3a6e' => 'Azul', '#c0392b' => 'Rojo'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '02166',
                    'nombre'         => 'Polera Polo M/L Mujer Piqué',
                    'alt'            => 'Polera Polo M/L Mujer',
                    'imagen'         => 'https://tworldstore.cl/3901-large_default/polera-polo-ml-mujer-60-alg-40-poly.jpg',
                    'especificacion' => '60% Algodón / 40% Poliéster · Piqué 230 gr · Manga Larga',
                    'colores'        => ['#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '02256',
                    'nombre'         => 'Polera Polo Dryfresh M/L Hombre',
                    'alt'            => 'Polera Polo Dryfresh M/L',
                    'imagen'         => 'https://tworldstore.cl/2430-large_default/polera-polo-dryfresh-ml-hombre-60-alg-40-poly.jpg',
                    'especificacion' => '60% Algodón / 40% Poliéster · Secado rápido · Manga Larga',
                    'colores'        => ['#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '02306',
                    'nombre'         => 'Polera Camisero Dryfresh Smooth M/L Hombre',
                    'alt'            => 'Polera Camisero Dryfresh',
                    'imagen'         => 'https://tworldstore.cl/3038-large_default/polera-c-camisero-dryfresh-smooth-hombre-ml.jpg',
                    'especificacion' => 'Jersey 180 gr · Secado rápido · UV · Manga Larga',
                    'colores'        => ['#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '02346',
                    'nombre'         => 'Polera Polo Comfort Spandex M/L Hombre',
                    'alt'            => 'Polera Polo Comfort M/L Hombre',
                    'imagen'         => 'https://tworldstore.cl/1577-large_default/polera-polo-comfort-spandex-ml-hombre.jpg',
                    'especificacion' => 'Spandex · Cuello con botones · Manga Larga',
                    'colores'        => ['#637282' => 'Gris', '#1a1a1a' => 'Negro', '#c0392b' => 'Rojo', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '02326',
                    'nombre'         => 'Polera Polo Comfort Spandex M/C Hombre',
                    'alt'            => 'Polera Polo Comfort M/C Hombre',
                    'imagen'         => 'https://tworldstore.cl/1528-large_default/polera-polo-comfort-spandex-mc-hombre.jpg',
                    'especificacion' => 'Spandex · Cuello con botones · Manga Corta',
                    'colores'        => ['#1e3a6e' => 'Azul', '#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#637282' => 'Gris', '#c0392b' => 'Rojo'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '02356',
                    'nombre'         => 'Polera Polo Comfort Spandex M/L Mujer',
                    'alt'            => 'Polera Polo Comfort M/L Mujer',
                    'imagen'         => 'https://tworldstore.cl/1602-large_default/polera-polo-comfort-spandex-ml-mujer.jpg',
                    'especificacion' => 'Spandex · Cuello con botones · Manga Larga',
                    'colores'        => ['#1e3a6e' => 'Azul', '#1a1a1a' => 'Negro', '#637282' => 'Gris', '#c0392b' => 'Rojo'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '02336',
                    'nombre'         => 'Polera Polo Comfort Spandex M/C Mujer',
                    'alt'            => 'Polera Polo Comfort M/C Mujer',
                    'imagen'         => 'https://tworldstore.cl/1552-large_default/polera-polo-comfort-spandex-mc-mujer.jpg',
                    'especificacion' => 'Spandex · Cuello con botones · Manga Corta',
                    'colores'        => ['#1e3a6e' => 'Azul', '#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#637282' => 'Gris', '#c0392b' => 'Rojo'],
                    'cta'            => 'Cotizar con bordado',
                ],
            ],
        ],

        'executive'   => [
            'tab'         => 'Executive',
            'badge'       => 'Executive Line',
            'titulo'      => 'Línea',
            'destacado'   => 'Ejecutiva',
            'descripcion' => 'Chaquetas premium, micropolar navigator y casacas térmicas para un look profesional de alto nivel.',
            'productos'   => [
                [
                    'sku'            => '03139',
                    'nombre'         => 'Micropolar Navigator M/L Hombre',
                    'alt'            => 'Micropolar Navigator',
                    'imagen'         => 'https://tworldstore.cl/504-large_default/micropolar-navigator-ml-hombre-100-poly.jpg',
                    'especificacion' => '100% Poliéster · Manga Larga · Premium',
                    'colores'        => ['#555' => 'Gris Oscuro', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '03149',
                    'nombre'         => 'Micropolar Navigator M/L Mujer',
                    'alt'            => 'Micropolar Navigator Mujer',
                    'imagen'         => 'https://tworldstore.cl/509-large_default/micropolar-navigator-ml-mujer-100-poly.jpg',
                    'especificacion' => '100% Poliéster · Corte femenino · Premium',
                    'colores'        => ['#555' => 'Gris Oscuro', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '08381',
                    'nombre'         => 'Chaqueta Executive Knit Fleece Hombre',
                    'alt'            => 'Chaqueta Executive Knit Fleece',
                    'imagen'         => 'https://tworldstore.cl/6009-large_default/chaqueta-executive-knit-fleece-hombre.jpg',
                    'especificacion' => 'Knit Fleece · Alta calidad · Manga Larga',
                    'colores'        => ['#1a1a1a' => 'Negro', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '08096',
                    'nombre'         => 'Chaqueta 3 en 1 Basic M/L Hombre',
                    'alt'            => 'Chaqueta 3 en 1',
                    'imagen'         => 'https://tworldstore.cl/657-large_default/chaqueta-3-en-1-basic-ml-hombre.jpg',
                    'especificacion' => 'Chaqueta exterior + forro polar desmontable',
                    'colores'        => ['#1a1a1a' => 'Negro', '#9e9e9e' => 'Gris', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '08309',
                    'nombre'         => 'Chaqueta 3 en 1 Premium M/L Hombre',
                    'alt'            => 'Chaqueta 3 en 1 Premium',
                    'imagen'         => 'https://tworldstore.cl/713-large_default/chaqueta-3-en-1-premium-ml-hombre.jpg',
                    'especificacion' => 'Premium · Forro polar desmontable · Impermeable',
                    'colores'        => ['#1a1a1a' => 'Negro', '#c0392b' => 'Rojo', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '08046',
                    'nombre'         => 'Casaca Térmica Pioneer Impermeable M/L Hombre',
                    'alt'            => 'Casaca Térmica Pioneer',
                    'imagen'         => 'https://tworldstore.cl/2613-large_default/casaca-termica-pionner-imperm-ml-hombre.jpg',
                    'especificacion' => 'Impermeable · Acolchada · Manga Larga',
                    'colores'        => ['#1a1a1a' => 'Negro', '#c0392b' => 'Rojo', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
            ],
        ],

        'advance'     => [
            'tab'         => 'Advance',
            'badge'       => 'Advance Line',
            'titulo'      => 'Tecnología',
            'destacado'   => 'avanzada',
            'descripcion' => 'Micropolar expedition, cortavientos high tech y chaquetas Sirius para condiciones exigentes.',
            'productos'   => [
                [
                    'sku'            => '03119',
                    'nombre'         => 'Micropolar Expedition M/L Hombre',
                    'alt'            => 'Micropolar Expedition',
                    'imagen'         => 'https://tworldstore.cl/1929-large_default/micropolar-expedition-ml-hombre-100-poly.jpg',
                    'especificacion' => '100% Poliéster · Alta lofting · Manga Larga',
                    'colores'        => ['#1a1a1a' => 'Negro', '#9e9e9e' => 'Gris', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '03129',
                    'nombre'         => 'Micropolar Expedition M/L Mujer',
                    'alt'            => 'Micropolar Expedition Mujer',
                    'imagen'         => 'https://tworldstore.cl/1931-large_default/micropolar-expedition-ml-mujer-100-poly.jpg',
                    'especificacion' => '100% Poliéster · Alta lofting · Corte femenino',
                    'colores'        => ['#1a1a1a' => 'Negro', '#9e9e9e' => 'Gris', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '07014',
                    'nombre'         => 'Cortaviento Basic M/L Hombre',
                    'alt'            => 'Cortaviento Basic',
                    'imagen'         => 'https://tworldstore.cl/2561-large_default/cortaviento-basic-ml-hombre.jpg',
                    'especificacion' => 'Cortaviento · Impermeable · Manga Larga',
                    'colores'        => ['#1a1a1a' => 'Negro', '#c0392b' => 'Rojo', '#3498db' => 'Azulino', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '27001',
                    'nombre'         => 'Cortaviento Limos High Tech M/L Hombre',
                    'alt'            => 'Cortaviento Limos High Tech',
                    'imagen'         => 'https://tworldstore.cl/831-large_default/cortaviento-limos-high-tech-ml-hombre.jpg',
                    'especificacion' => 'High Tech · Antiviento · Manga Larga',
                    'colores'        => ['#1a1a1a' => 'Negro', '#c0392b' => 'Rojo', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '08650',
                    'nombre'         => 'Chaqueta Advance Sirius Hombre M/L',
                    'alt'            => 'Chaqueta Sirius',
                    'imagen'         => 'https://tworldstore.cl/3640-large_default/chaqueta-advance-line-sirius-hombre-ml.jpg',
                    'especificacion' => 'Premium · Softshell · Manga Larga',
                    'colores'        => ['#1a1a1a' => 'Negro', '#9e9e9e' => 'Gris'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '07024',
                    'nombre'         => 'Cortaviento Basic M/L Mujer',
                    'alt'            => 'Cortaviento Basic Mujer',
                    'imagen'         => 'https://tworldstore.cl/4802-large_default/cortaviento-basic-ml-mujer.jpg',
                    'especificacion' => 'Cortaviento · Impermeable · Corte femenino',
                    'colores'        => ['#1a1a1a' => 'Negro', '#c0392b' => 'Rojo', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
            ],
        ],

        'practical'   => [
            'tab'         => 'Practical',
            'badge'       => 'Practical Line',
            'titulo'      => 'Funcional y',
            'destacado'   => 'resistente',
            'descripcion' => 'La línea más completa: polares, parkas térmicas, jeans, pantalones cargo, softshells y bandanas para todo terreno.',
            'productos'   => [
                [
                    'sku'            => '13069',
                    'nombre'         => 'Primera Capa Practical Line Hombre M/Larga',
                    'alt'            => 'Primera Capa Practical',
                    'imagen'         => 'https://tworldstore.cl/5682-large_default/primera-capa-practical-line-hombre-mlarga.jpg',
                    'especificacion' => 'Térmica · Manga Larga · Color Negro',
                    'colores'        => ['#1a1a1a' => 'Negro'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '08411',
                    'nombre'         => 'Parka Térmica Practical Line M/L Hombre',
                    'alt'            => 'Parka Térmica Practical',
                    'imagen'         => 'https://tworldstore.cl/6129-large_default/parka-termica-practical-line-manga-larga-hombre.jpg',
                    'especificacion' => 'Impermeable · Acolchada · Manga Larga',
                    'colores'        => ['#1a1a1a' => 'Negro', '#c0392b' => 'Rojo', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '10201',
                    'nombre'         => 'Jeans Practical Line 100% Algodón Hombre',
                    'alt'            => 'Jeans Practical Line',
                    'imagen'         => 'https://tworldstore.cl/6312-large_default/jeans-practical-line-100-algodon-hombre.jpg',
                    'especificacion' => '100% Algodón · Resistente · Color Azul',
                    'colores'        => ['#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar',
                ],
                [
                    'sku'            => '10582',
                    'nombre'         => 'Pantalón Cargo Gabardina Forro Polar Hombre',
                    'alt'            => 'Pantalón Cargo Gabardina',
                    'imagen'         => 'https://tworldstore.cl/6138-large_default/pantalon-cargo-gabardina-forro-polar-hombre.jpg',
                    'especificacion' => 'Gabardina · Forro polar · Bolsillos cargo',
                    'colores'        => ['#1a1a1a' => 'Negro', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar',
                ],
                [
                    'sku'            => '08520',
                    'nombre'         => 'Chaqueta Softshell Rhelmu M/L Hombre',
                    'alt'            => 'Chaqueta Softshell Rhelmu',
                    'imagen'         => 'https://tworldstore.cl/2705-large_default/chaqueta-softshell-rhelmu-ml-hombre-100-poly.jpg',
                    'especificacion' => '100% Poliéster · Softshell · Antiviento',
                    'colores'        => ['#555' => 'Gris Oscuro', '#1a1a1a' => 'Negro', '#c0392b' => 'Rojo', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '03219',
                    'nombre'         => 'Micropolar Practical C/Reflectiva Hombre',
                    'alt'            => 'Micropolar Practical Reflectiva',
                    'imagen'         => 'https://tworldstore.cl/3163-large_default/micropolar-practical-line-creflectiva-hombre.jpg',
                    'especificacion' => 'Cinta reflectiva · Seguridad · Varios colores',
                    'colores'        => ['#555' => 'Gris Oscuro', '#1a1a1a' => 'Negro', '#c0392b' => 'Rojo', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '08610',
                    'nombre'         => 'Chaqueta Practical Resist Hombre M/L',
                    'alt'            => 'Chaqueta Practical Resist',
                    'imagen'         => 'https://tworldstore.cl/4923-large_default/chaqueta-practical-line-resist-hombre-ml.jpg',
                    'especificacion' => 'Alta resistencia · Bicolor · Manga Larga',
                    'colores'        => ['#1e3a6e' => 'Azul/Azul Indigo', '#1a1a1a' => 'Negro/Gris Oscuro'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '55141',
                    'nombre'         => 'Bandana Practical Line Unisex',
                    'alt'            => 'Bandana Practical',
                    'imagen'         => 'https://tworldstore.cl/6117-large_default/bandana-practical-line-unisex.jpg',
                    'especificacion' => 'Multifuncional · Color Negro',
                    'colores'        => ['#1a1a1a' => 'Negro'],
                    'cta'            => 'Cotizar con estampado',
                ],
                [
                    'sku'            => '11131',
                    'nombre'         => 'Overol Gabardina Practical Line Hombre M/Larga',
                    'alt'            => 'Overol Gabardina Practical Line',
                    'imagen'         => 'https://tworldstore.cl/2012-large_default/overol-gabardina-practical-line-hombre-mlarga.jpg',
                    'especificacion' => '100% Poliéster · Gabardina 180 gr · Manga Larga',
                    'colores'        => ['#1e3a6e' => 'Azul', '#9e9e9e' => 'Gris', '#c0392b' => 'Rojo', '#e67e22' => 'Naranjo'],
                    'cta'            => 'Cotizar con bordado',
                ],
            ],
        ],

        'free-action' => [
            'tab'         => 'Free Action',
            'badge'       => 'Free Action Line',
            'titulo'      => 'Libertad de',
            'destacado'   => 'movimiento',
            'descripcion' => 'Jeans y chaquetas con máxima flexibilidad para trabajo activo. Diseño moderno y confort superior.',
            'productos'   => [
                [
                    'sku'            => '10202',
                    'nombre'         => 'Jeans Free Action Line Hombre',
                    'alt'            => 'Jeans Free Action',
                    'imagen'         => 'https://tworldstore.cl/6178-large_default/jeans-free-action-line-hombre.jpg',
                    'especificacion' => 'Máxima elasticidad · Resistente · Color Azul',
                    'colores'        => ['#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar',
                ],
                [
                    'sku'            => '10212',
                    'nombre'         => 'Jeans Free Action Line Mujer',
                    'alt'            => 'Jeans Free Action Mujer',
                    'imagen'         => 'https://tworldstore.cl/6182-large_default/jeans-free-action-line-mujer.jpg',
                    'especificacion' => 'Máxima elasticidad · Corte femenino · Color Azul',
                    'colores'        => ['#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar',
                ],
                [
                    'sku'            => '08640',
                    'nombre'         => 'Chaqueta Free Action Expert Hombre M/L',
                    'alt'            => 'Chaqueta Free Action Expert',
                    'imagen'         => 'https://tworldstore.cl/3476-large_default/chaqueta-free-action-line-expert-hombre-ml.jpg',
                    'especificacion' => 'Softshell elástico · Libertad de movimiento · Bicolor',
                    'colores'        => ['#555' => 'Gris/Negro', '#1e3a6e' => 'Azul/Azul Indigo'],
                    'cta'            => 'Cotizar con bordado',
                ],
            ],
        ],

        'hi-vis'      => [
            'tab'         => 'Hi-Vis',
            'badge'       => 'Hi-Vis Line',
            'titulo'      => 'Alta',
            'destacado'   => 'visibilidad',
            'descripcion' => 'Ropa de alta visibilidad certificada Clase 2 y Clase 3. Parkas, micropolar, poleras y jardineras para faenas que exigen seguridad.',
            'productos'   => [
                [
                    'sku'            => '01321',
                    'nombre'         => 'Polera Híbrida Dual Hi-Vis M/Corta Hombre',
                    'alt'            => 'Polera Híbrida Dual Hi-Vis',
                    'imagen'         => 'https://tworldstore.cl/2765-large_default/polera-hibrida-dual-hi-vis-hombre-mcorta.jpg',
                    'especificacion' => 'Alta Visibilidad · Bicolor · Manga Corta',
                    'colores'        => ['#9e9e9e' => 'Gris', '#c0392b' => 'Rojo', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar',
                ],
                [
                    'sku'            => '01341',
                    'nombre'         => 'Polera Híbrida Dual Hi-Vis M/Larga Hombre',
                    'alt'            => 'Polera Híbrida Dual Hi-Vis M/L',
                    'imagen'         => 'https://tworldstore.cl/4334-large_default/polera-hibrida-dual-hi-vis-hombre-mlarga.jpg',
                    'especificacion' => 'Alta Visibilidad · Bicolor · Manga Larga',
                    'colores'        => ['#9e9e9e' => 'Gris', '#c0392b' => 'Rojo', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar',
                ],
                [
                    'sku'            => '03199',
                    'nombre'         => 'Micropolar Hi-Vis Clase 2 Bicolor M/L Hombre',
                    'alt'            => 'Micropolar Hi-Vis Clase 2',
                    'imagen'         => 'https://tworldstore.cl/3254-large_default/micropolar-hi-vis-clase-2-bi-color-ml-hombre.jpg',
                    'especificacion' => 'Certificado Clase 2 · Alta visibilidad · Bicolor',
                    'colores'        => ['#f1c40f' => 'Amarillo/Gris Oscuro', '#e67e22' => 'Naranjo/Gris Oscuro'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '08401',
                    'nombre'         => 'Parka Térmica Alta Visibilidad M/L Hombre',
                    'alt'            => 'Parka Térmica Alta Visibilidad',
                    'imagen'         => 'https://tworldstore.cl/1699-large_default/parka-termica-alta-visibilidad-ml-hombre.jpg',
                    'especificacion' => 'Impermeable · Alta Visibilidad · Varios colores bicolor',
                    'colores'        => ['#f1c40f' => 'Amarillo/Gris Oscuro', '#e67e22' => 'Naranjo/Gris Oscuro', '#c0392b' => 'Rojo/Gris Oscuro'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '08501',
                    'nombre'         => 'Chaqueta Softshell Alta Visibilidad M/L Hombre',
                    'alt'            => 'Chaqueta Softshell Alta Visibilidad',
                    'imagen'         => 'https://tworldstore.cl/1898-large_default/chaqueta-softshell-alta-visibilidad-ml-hombre.jpg',
                    'especificacion' => 'Softshell · Alta Visibilidad · Bicolor',
                    'colores'        => ['#f1c40f' => 'Amarillo/Gris Oscuro', '#e67e22' => 'Naranjo/Gris Oscuro'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '08660',
                    'nombre'         => 'Parka Térmica Alta Visibilidad Clase 3 M/L Hombre',
                    'alt'            => 'Parka Clase 3',
                    'imagen'         => 'https://tworldstore.cl/6065-large_default/parka-termica-alta-visibilidad-clase-3-ml-hombre.jpg',
                    'especificacion' => 'Certificado Clase 3 · Impermeable · Acolchada',
                    'colores'        => ['#f1c40f' => 'Amarillo', '#e67e22' => 'Naranjo', '#8b0000' => 'Rojo Minero'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '30326',
                    'nombre'         => 'Jardinera Térmica Hi-Vis Certificada Hombre',
                    'alt'            => 'Jardinera Térmica Hi-Vis',
                    'imagen'         => 'https://tworldstore.cl/6074-large_default/jardinera-termica-hi-vis-certificada-hombre-100-poly.jpg',
                    'especificacion' => '100% Poliéster · Certificada Clase 2 · Acolchada',
                    'colores'        => ['#f1c40f' => 'Amarillo', '#e67e22' => 'Naranjo', '#8b0000' => 'Rojo Minero'],
                    'cta'            => 'Cotizar',
                ],
            ],
        ],

        'iron'        => [
            'tab'         => 'Iron',
            'badge'       => 'Iron Line',
            'titulo'      => 'Resistencia',
            'destacado'   => 'extrema',
            'descripcion' => 'Línea de alta resistencia con micropolar y chaquetas Ónix para condiciones de trabajo exigentes.',
            'productos'   => [
                [
                    'sku'            => '03239',
                    'nombre'         => 'Micropolar Iron Line C/Reflectiva M/L Hombre',
                    'alt'            => 'Micropolar Iron Line',
                    'imagen'         => 'https://tworldstore.cl/3232-large_default/micropolar-iron-line-creflectiva-ml-hombre.jpg',
                    'especificacion' => 'Cinta reflectiva · Alta resistencia · Gris Oscuro',
                    'colores'        => ['#555' => 'Gris Oscuro'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '08600',
                    'nombre'         => 'Chaqueta Iron Line Ónix Hombre M/L',
                    'alt'            => 'Chaqueta Iron Ónix',
                    'imagen'         => 'https://tworldstore.cl/3659-large_default/chaqueta-iron-line-onix-hombre-ml.jpg',
                    'especificacion' => 'Ultra resistente · Bicolor · Manga Larga',
                    'colores'        => ['#1e3a6e' => 'Azul/Negro', '#555' => 'Negro/Gris Oscuro'],
                    'cta'            => 'Cotizar con bordado',
                ],
            ],
        ],

        'outwork'     => [
            'tab'         => 'Outwork',
            'badge'       => 'Outwork Line',
            'titulo'      => 'Diseñada para el',
            'destacado'   => 'exterior',
            'descripcion' => 'Camisas Ripstop, blusas, micropolar y gorros reflectivos para trabajo en exteriores con estilo.',
            'productos'   => [
                [
                    'sku'            => '06004',
                    'nombre'         => 'Camisa Outwork Ripstop Jubae M/L Hombre',
                    'alt'            => 'Camisa Outwork Ripstop',
                    'imagen'         => 'https://tworldstore.cl/4763-large_default/camisa-outwork-ripstop-jubae-ml-hombre.jpg',
                    'especificacion' => 'Tela Ripstop · Alta resistencia · 6 colores',
                    'colores'        => ['#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#a8c5da' => 'Celeste Claro', '#2d5a1b' => 'Verde Musgo', '#c8b87d' => 'Khaki', '#1a4f8b' => 'Azul Royal'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '06005',
                    'nombre'         => 'Blusa Outwork Ripstop Jubae M/L Mujer',
                    'alt'            => 'Blusa Outwork Ripstop Mujer',
                    'imagen'         => 'https://tworldstore.cl/5804-large_default/blusa-outwork-ripstop-jubae-ml-mujer.jpg',
                    'especificacion' => 'Tela Ripstop · Corte femenino · Varios colores',
                    'colores'        => ['#fff' => 'Blanco', '#1a1a1a' => 'Negro', '#a8c5da' => 'Celeste Claro'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '06361',
                    'nombre'         => 'Camisa Outwork Salvia Hombre M/L',
                    'alt'            => 'Camisa Outwork Salvia',
                    'imagen'         => 'https://tworldstore.cl/3444-large_default/camisa-outwork-salvia-hombre-ml.jpg',
                    'especificacion' => 'Premium Outwork · Manga Larga · Colores neutros',
                    'colores'        => ['#a8c5da' => 'Celeste Claro', '#c8b87d' => 'Taupe'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '06381',
                    'nombre'         => 'Camisa Outwork Abelia Hombre M/L',
                    'alt'            => 'Camisa Outwork Abelia',
                    'imagen'         => 'https://tworldstore.cl/3438-large_default/camisa-outwork-abelia-hombre-ml.jpg',
                    'especificacion' => 'Diseño moderno · Manga Larga · 3 colores',
                    'colores'        => ['#fff' => 'Blanco', '#c8b87d' => 'Taupe', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '03259',
                    'nombre'         => 'Micropolar Outwork Hombre M/L',
                    'alt'            => 'Micropolar Outwork',
                    'imagen'         => 'https://tworldstore.cl/5916-large_default/micropolar-outwork-hombre-ml.jpg',
                    'especificacion' => 'Premium · Alta lofting · Producto testeado',
                    'colores'        => ['#1a1a1a' => 'Negro', '#9e9e9e' => 'Gris'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '04209',
                    'nombre'         => 'Gorro Outwork Reflex Unisex',
                    'alt'            => 'Gorro Outwork Reflex',
                    'imagen'         => 'https://tworldstore.cl/6043-large_default/gorro-outwork-reflex-unisex.jpg',
                    'especificacion' => 'Cinta reflectiva · Unisex · Color Negro',
                    'colores'        => ['#1a1a1a' => 'Negro'],
                    'cta'            => 'Cotizar con bordado',
                ],
            ],
        ],

        'technic'     => [
            'tab'         => 'Technic',
            'badge'       => 'Technic Line',
            'titulo'      => 'Ignífuga y',
            'destacado'   => 'antiestática',
            'descripcion' => 'Ropa certificada ignífuga y antiestática para faenas de alto riesgo. Camisas, overoles, chaquetas y pantalones en algodón.',
            'productos'   => [
                [
                    'sku'            => '46010',
                    'nombre'         => 'Camisa Ignífuga Antiestática Technic M/L Hombre',
                    'alt'            => 'Camisa Ignífuga Antiestática',
                    'imagen'         => 'https://tworldstore.cl/6198-large_default/camisa-ignifuga-antiestatica-technic-m-l-hombre-97-alg-3-f-carbon.jpg',
                    'especificacion' => '97% Algodón / 3% Fibra de Carbono · Certificada · Azul',
                    'colores'        => ['#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar',
                ],
                [
                    'sku'            => '51068',
                    'nombre'         => 'Overol Ignífugo Antiestático Technic Hombre',
                    'alt'            => 'Overol Ignífugo',
                    'imagen'         => 'https://tworldstore.cl/6202-large_default/overol-ignifugo-antiestatico-technic-hombre-100-alg.jpg',
                    'especificacion' => '100% Algodón · Certificado · Color Azul',
                    'colores'        => ['#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar',
                ],
                [
                    'sku'            => '48078',
                    'nombre'         => 'Chaqueta Ignífuga Antiestática Technic M/L Hombre',
                    'alt'            => 'Chaqueta Ignífuga Antiestática',
                    'imagen'         => 'https://tworldstore.cl/6203-large_default/chaqueta-ignifuga-antiestatica-technic-m-l-hombre-100-alg.jpg',
                    'especificacion' => '100% Algodón · Certificada · Azulino',
                    'colores'        => ['#3498db' => 'Azulino'],
                    'cta'            => 'Cotizar',
                ],
                [
                    'sku'            => '50078',
                    'nombre'         => 'Pantalón Ignífugo Antiestático Technic Hombre',
                    'alt'            => 'Pantalón Ignífugo',
                    'imagen'         => 'https://tworldstore.cl/6204-large_default/pantalon-ignifugo-antiestatico-technic-hombre-100-alg.jpg',
                    'especificacion' => '100% Algodón · Certificado · Azulino',
                    'colores'        => ['#3498db' => 'Azulino'],
                    'cta'            => 'Cotizar',
                ],
                [
                    'sku'            => '08324',
                    'nombre'         => 'Chaqueta Térmica Premium M/L Hombre',
                    'alt'            => 'Chaqueta Térmica Premium',
                    'imagen'         => 'https://tworldstore.cl/717-large_default/chaqueta-termica-premium-ml-hombre.jpg',
                    'especificacion' => 'Acolchada · 5 colores disponibles · Manga Larga',
                    'colores'        => ['#1a1a1a' => 'Negro', '#9e9e9e' => 'Gris', '#c0392b' => 'Rojo', '#3498db' => 'Azulino', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
                [
                    'sku'            => '08279',
                    'nombre'         => 'Chaqueta Térmica Navigator M/L Hombre High Tech',
                    'alt'            => 'Chaqueta Térmica Navigator',
                    'imagen'         => 'https://tworldstore.cl/3186-large_default/chaqueta-termica-navigator-ml-hombre-high-tech.jpg',
                    'especificacion' => 'High Tech · Acolchada · Negro o Azul',
                    'colores'        => ['#1a1a1a' => 'Negro', '#1e3a6e' => 'Azul'],
                    'cta'            => 'Cotizar con bordado',
                ],
            ],
        ],
    ];
}

/**
 * Número total de prendas del catálogo, para no repetir cifras a mano.
 */
function catalogo_total(): int {
    $total = 0;
    foreach (catalogo_lineas() as $linea) {
        $total += count($linea['productos']);
    }
    return $total;
}

/**
 * Valida un color del catálogo antes de usarlo como valor CSS.
 * Los puntos de color son dato, no maquetación: el único sitio donde se
 * inyecta un color es el atributo style del punto, y solo si es un hex válido.
 */
function catalogo_color_css(string $hex): string {
    return preg_match('/^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/', $hex) === 1 ? $hex : 'transparent';
}
